---
driver:
  name: terraform

provisioner:
  name: terraform

platforms:
- name: local

verifier:
  name: terraform

suites:
  - name: aws_chef_automate
    driver:
      name: terraform
      command_timeout: 1800
      root_module_directory: test/fixtures/aws_chef_automate
    verifier:
      systems:
        - name: default
          backend: local
          attrs:
            - test/integration/aws_chef_automate/attrs.yml
  - name: aws_chef_automate_chef_server
    driver:
      name: terraform
      command_timeout: 1800
      root_module_directory: test/fixtures/aws_chef_automate_chef_server
    verifier:
      systems:
        - name: chef_server
          backend: local
          attrs:
            - test/integration/aws_chef_automate_chef_server/attrs.yml
